#!/usr/bin/env bash
# prints for domains and sub-domains

func_domain_subdomain () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g"
}

if [ "$#" -eq 2 ]
then
	func_domain_subdomain "$2.$1" "$2"
else
	func_domain_subdomain "www.$1" "www"
	func_domain_subdomain "lb-01.$1" "lb-01"
	func_domain_subdomain "web-01.$1" "web-01"
	func_domain_subdomain "web-02.$1" "web-02"
fi
