#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Set the current date
date=$(date +"%d-%m-%Y")

# Set the MySQL root password
password="$1"

# Generate the MySQL dump
mysqldump -uroot -p"$password" --all-databases > backup.sql

# Compress the MySQL dump into a tar.gz archive
tar -czvf $date.tar.gz backup.sql
