#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times
#+but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -lt 10 ];
do
	echo "Best School"
	((i++))
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
done
