#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#+display hours from 0 to 12
#+display minutes from 1 to 59
hours=0

# Use while loop to increment hours
while [ $hours -lt 13 ]
do
  echo "Hour: $hours"
  minutes=1
  # Use while loop to increment minutes
  while [ $minutes -lt 60 ]
  do
    echo $minutes
    minutes=$((minutes+1))
  done
  hours=$((hours+1))
done
