#!/usr/bin/env bash
# A Bash script that gives information about the "school" file
for file in school
do
	if [ -e "$file" ]
	then
		echo "school file exists"
	else
		echo "school file does not exist"
	fi

	if [ -z "$file" ]
	then
		echo "school file is empty"
	elif [ ! -z "$file" ]
	then
		echo "school file is not empty"
	elif [ -f "$file" ]
	then
		echo "school is a regular file"
	else
		echo ""
	fi
done
