#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#+display hours from 0 to 12
#+display minutes from 1 to 59
i=1
while [ $i -le 60 ]
do
	case $i in
		1)
			echo "Hour: 0"
			;;
		60)
			echo "Hour: 1"
			;;
	esac
	echo "$i"
	i=$((i + 1))
done
