#!/usr/bin/env bash
# In this first debugging project, you will need to get Apache to run on the
# container and to return a page containing
# Hello Holberton when querying the root of it.
docker pull httpd
FROM httpd:latest
RUN echo 'Hello Holberton' > /usr/local/apache2htdocs/index.html
docker build -t my-apache-image .
docker run -p 8080:80 -d my-apache-image
curl 0:8080