#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client,
# let’s configure it to our needs so that you can connect to a 
# server without typing a password.
Host ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no